# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe5\x9c\xb0\xe5\x90\x8d')),
                ('code', models.CharField(max_length=255, verbose_name=b'\xe4\xbb\xa3\xe7\xa0\x81')),
                ('type', models.IntegerField(choices=[(0, b'\xe5\x9b\xbd\xe5\xae\xb6'), (1, b'\xe7\x9c\x81'), (2, b'\xe5\xb8\x82'), (3, b'\xe5\x8c\xba\xe5\x8e\xbf')], verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('parent', models.IntegerField(verbose_name=b'\xe7\x88\xb6\xe7\xba\xa7\xe7\xbc\x96\xe5\x8f\xb7(\xe5\x85\xb3\xe8\x81\x94\xe8\x87\xaa\xe5\xb7\xb2)')),
            ],
            options={
                'verbose_name': '\u6240\u5728\u5730',
                'verbose_name_plural': '\u6240\u5728\u5730',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name=b'\xe6\xb6\x88\xe6\x81\xaf')),
                ('addtime', models.DateTimeField(auto_now=True, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xb6\xe9\x97\xb4')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Category', verbose_name=b'\xe6\x9d\xa5\xe6\xba\x90')),
            ],
            options={
                'verbose_name': '\u6d88\u606f',
                'verbose_name_plural': '\u6d88\u606f',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('password', models.CharField(max_length=100, verbose_name=b'\xe5\xaf\x86\xe7\xa0\x81')),
                ('realname', models.CharField(max_length=20, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d')),
                ('email', models.EmailField(max_length=254, verbose_name=b'Email')),
                ('face', models.ImageField(blank=True, default=b'', upload_to=b'face/%Y/%m/%d', verbose_name=b'\xe5\xa4\xb4\xe5\x83\x8f')),
                ('url', models.CharField(blank=True, default=b'', max_length=200, verbose_name=b'\xe4\xb8\xaa\xe4\xba\xba\xe4\xb8\xbb\xe9\xa1\xb5')),
                ('about', models.TextField(blank=True, default=b'', max_length=1000, verbose_name=b'\xe5\x85\xb3\xe4\xba\x8e\xe6\x88\x91')),
                ('addtime', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\xb3\xa8\xe5\x86\x8c\xe6\x97\xb6\xe9\x97\xb4')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Area', verbose_name=b'\xe5\x9c\xb0\xe5\x8c\xba')),
                ('friend', models.ManyToManyField(related_name='_user_friend_+', to='mvc.User', verbose_name=b'\xe6\x9c\x8b\xe5\x8f\x8b')),
            ],
            options={
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.User', verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe8\x80\x85'),
        ),
    ]
